# Generated by Django 4.2.5 on 2023-09-18 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('conexoes', models.ManyToManyField(blank=True, to='metro.estacao')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro.linha')),
            ],
            options={
                'verbose_name': 'estação',
                'verbose_name_plural': 'estações',
                'ordering': ['ordem'],
                'unique_together': {('nome', 'linha')},
            },
        ),
    ]
