# Generated by Django 4.2.5 on 2023-09-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_destino'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={'ordering': ['ordem']},
        ),
        migrations.RemoveField(
            model_name='destino',
            name='estacoes',
        ),
        migrations.AddField(
            model_name='destino',
            name='destino',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='estacao_destino', to='metro.estacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destino',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destino',
            name='origem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='estacao_origem', to='metro.estacao'),
            preserve_default=False,
        ),
    ]
