# Generated by Django 4.2.5 on 2023-09-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0003_alter_destino_options_remove_destino_estacoes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destino',
        ),
    ]
