# Generated by Django 4.2.5 on 2023-09-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0004_delete_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacao_destino', to='metro.estacao')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacao_origem', to='metro.estacao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
