# Generated by Django 4.2.5 on 2023-09-21 11:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0005_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='linha',
            name='cor',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
